# Generated by Django 5.2.1 on 2025-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_soil_sensordata_soil_moisture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='기준 토양습도 (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
