# Generated by Django 5.2.1 on 2025-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_soilmoisturethreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='기준 습도 (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
