# Generated by Django 5.2.1 on 2025-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_humiditythreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_function_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_at', models.DateTimeField()),
            ],
        ),
    ]
