# Generated by Django 5.2.1 on 2025-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_function_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_function_date',
            name='function_at',
        ),
        migrations.AddField(
            model_name='auto_function_date',
            name='humidifier_function_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auto_function_date',
            name='pump_function_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
